# Generated by Django 5.0.6 on 2026-01-23 17:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Javob', 'verbose_name_plural': 'Javoblar'},
        ),
        migrations.AlterModelOptions(
            name='botstate',
            options={'verbose_name': 'Bot holati', 'verbose_name_plural': 'Bot holatlari'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikatlar'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['grade', 'title'], 'verbose_name': 'Imtihon', 'verbose_name_plural': 'Imtihonlar'},
        ),
        migrations.AlterModelOptions(
            name='examattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Imtihon topshirish', 'verbose_name_plural': 'Imtihon topshirishlar'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fikr-mulohaza', 'verbose_name_plural': 'Fikr-mulohazalar'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Ota-ona', 'verbose_name_plural': 'Ota-onalar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['exam', 'question_number'], 'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='registrationsource',
            options={'verbose_name': "Ro'yxatdan o'tish manbasi", 'verbose_name_plural': "Ro'yxatdan o'tish manbalari"},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': "O'quvchi", 'verbose_name_plural': "O'quvchilar"},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': "O'qituvchi", 'verbose_name_plural': "O'qituvchilar"},
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi"),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tuman/shahar'),
        ),
        migrations.AddField(
            model_name='student',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Metirka raqami'),
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', "O'zbekcha"), ('ru', 'Ruscha'), ('en', 'Inglizcha')], max_length=50, null=True, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, choices=[('Andijon', 'Andijon viloyati'), ('Buxoro', 'Buxoro viloyati'), ("Farg'ona", "Farg'ona viloyati"), ('Jizzax', 'Jizzax viloyati'), ('Namangan', 'Namangan viloyati'), ('Navoiy', 'Navoiy viloyati'), ('Qashqadaryo', 'Qashqadaryo viloyati'), ('Samarqand', 'Samarqand viloyati'), ('Sirdaryo', 'Sirdaryo viloyati'), ('Surxondaryo', 'Surxondaryo viloyati'), ('Toshkent', 'Toshkent viloyati'), ('Xorazm', 'Xorazm viloyati')], max_length=255, null=True, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=255, verbose_name='Javob matni'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Javob berilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='admin_panel.examattempt', verbose_name='Imtihon topshirish'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name="To'g'ri"),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points_earned',
            field=models.IntegerField(default=0, verbose_name='Olingan ball'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='admin_panel.question', verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='botstate',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='botstate',
            name='state_data',
            field=models.JSONField(blank=True, default=dict, verbose_name="Holat ma'lumotlari"),
        ),
        migrations.AlterField(
            model_name='botstate',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='botstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='admin_panel.examattempt', verbose_name='Imtihon topshirish'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Sertifikat raqami'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='admin_panel.exam', verbose_name='Imtihon'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Rasm yo'li"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="PDF fayl yo'li"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='admin_panel.student', verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.IntegerField(help_text='Imtihon davomiyligi daqiqalarda', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Davomiyligi (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.IntegerField(choices=[(5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf')], verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.IntegerField(help_text="O'tish uchun minimal foiz", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="O'tish balli (%)"),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Jami savollar'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='earned_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Olingan ball'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='admin_panel.exam', verbose_name='Imtihon'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Muddati tugaydi'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.IntegerField(blank=True, help_text='Foizda ball', null=True, verbose_name='Ball (%)'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='admin_panel.student', verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='total_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jami ball'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, help_text='1 dan 5 gacha baholash', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='admin_panel.student', verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='relationship',
            field=models.CharField(blank=True, help_text='Masalan: Ona, Ota, Vasiy', max_length=50, null=True, verbose_name='Qarindoshlik darajasi'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='admin_panel.student', verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=255, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='admin_panel.exam', verbose_name='Imtihon'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Savol raqami'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='registrationsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='registrationsource',
            name='source_details',
            field=models.TextField(blank=True, null=True, verbose_name='Manba tafsilotlari'),
        ),
        migrations.AlterField(
            model_name='registrationsource',
            name='source_type',
            field=models.CharField(help_text='Masalan: Tavsiya, Reklama, Maktab, Ijtimoiy tarmoq', max_length=100, verbose_name='Manba turi'),
        ),
        migrations.AlterField(
            model_name='registrationsource',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_source', to='admin_panel.student', verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf')], null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(8)], verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='students/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Maktab nomi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Foydalanuvchi nomi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='admin_panel.student', verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fan'),
        ),
    ]
