# Generated by Django 5.0.6 on 2026-01-23 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_answer_options_alter_botstate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='parent',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)], verbose_name='Yoshi'),
        ),
        migrations.AddField(
            model_name='parent',
            name='children_count',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], null=True, verbose_name='Farzandlar soni'),
        ),
        migrations.AddField(
            model_name='parent',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami 2'),
        ),
        migrations.AddField(
            model_name='parent',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kasbi'),
        ),
        migrations.AddField(
            model_name='student',
            name='achievements_description',
            field=models.TextField(blank=True, null=True, verbose_name='Avvalgi yutuqlar izohi'),
        ),
        migrations.AddField(
            model_name='student',
            name='achievements_file',
            field=models.FileField(blank=True, null=True, upload_to='students/achievements/', verbose_name='Avvalgi yutuqlar fayli/rasmi'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sharif'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ish joyi'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami 1'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='relationship',
            field=models.CharField(blank=True, choices=[('ota', 'Ota'), ('ona', 'Ona'), ('aka', 'Aka'), ('opa', 'Opa'), ('buvi', 'Buvi'), ('bobo', 'Bobo'), ('vasiy', 'Vasiy'), ('boshqa', 'Boshqa')], max_length=50, null=True, verbose_name='Kimligi'),
        ),
        migrations.AlterField(
            model_name='registrationsource',
            name='source_type',
            field=models.CharField(choices=[('telegram', 'Telegram kanal/guruh'), ('maktab', 'Maktab orqali'), ('ustoz', 'Ustoz tavsiyasi'), ('dost', "Do'st/tanish"), ('instagram', 'Instagram/TikTok'), ('boshqa', 'Boshqa')], max_length=100, verbose_name='Manba turi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Metrika raqami'),
        ),
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz')], max_length=50, null=True, verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Rasm'),
        ),
    ]
