# Generated by Django 5.0.6 on 2026-01-23 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_teacher_subject_parent_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('grade', models.IntegerField(choices=[(5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf')], help_text='Majburiy: test qaysi sinf uchun', verbose_name='Sinf')),
                ('duration_minutes', models.IntegerField(help_text='Test davomiyligi daqiqalarda', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Davomiyligi (daqiqa)')),
                ('version', models.CharField(blank=True, help_text="Test versiyasi (masalan: v1, v2) - bir sinfga bir nechta test bo'lishi uchun", max_length=50, null=True, verbose_name='Versiya')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'db_table': 'tests',
                'ordering': ['grade', 'title', 'version'],
                'indexes': [models.Index(fields=['grade', 'is_active'], name='tests_grade_f7c5c7_idx'), models.Index(fields=['grade', 'version'], name='tests_grade_2a5d3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Savol raqami')),
                ('type', models.CharField(choices=[('TEXT', 'Matn'), ('IMAGE', 'Rasm')], default='TEXT', help_text='Savol turi: Matn yoki Rasm', max_length=10, verbose_name='Tur')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('image_file_id', models.CharField(blank=True, help_text="Telegram file_id agar rasm bo'lsa", max_length=255, null=True, verbose_name='Rasm file_id')),
                ('option_a', models.CharField(max_length=500, verbose_name='Variant A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Variant B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Variant C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Variant D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('ball_weight', models.IntegerField(blank=True, default=1, help_text="Savolning og'irligi (ball)", null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Ball og'irligi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='admin_panel.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test savoli',
                'verbose_name_plural': 'Test savollari',
                'db_table': 'test_questions',
                'ordering': ['test', 'question_number'],
                'indexes': [models.Index(fields=['test', 'question_number'], name='test_questi_test_id_0a5c1a_idx')],
                'unique_together': {('test', 'question_number')},
            },
        ),
    ]
