# Generated by Django 5.0.6 on 2026-01-23 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_test_testquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_PROGRESS', 'Jarayonda'), ('FINISHED_REVIEW', 'Tekshiruvda'), ('SUBMITTED_FINAL', 'Yakuniy topshirilgan'), ('TIME_EXPIRED', 'Vaqt tugagan')], default='PENDING', max_length=20, verbose_name='Holat')),
                ('score', models.FloatField(blank=True, help_text='Foizda ball', null=True, verbose_name='Ball (%)')),
                ('total_points', models.FloatField(blank=True, null=True, verbose_name='Jami ball')),
                ('earned_points', models.FloatField(blank=True, null=True, verbose_name='Olingan ball')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Topshirilgan vaqt')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Muddati tugaydi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='admin_panel.student', verbose_name="O'quvchi")),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='admin_panel.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test topshirish',
                'verbose_name_plural': 'Test topshirishlar',
                'db_table': 'test_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Yuborilgan (boshlamagan)'), ('IN_PROGRESS', 'Jarayonda'), ('FINISHED_REVIEW', 'Tekshiruvda'), ('SUBMITTED_FINAL', 'Yakuniy topshirgan'), ('TIME_EXPIRED', 'Vaqt tugagan')], default='ASSIGNED', max_length=20, verbose_name='Holat')),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='Oxirgi marta test bilan ishlash vaqti', null=True, verbose_name='Oxirgi faollik')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_assignments', to='admin_panel.student', verbose_name="O'quvchi")),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='admin_panel.test', verbose_name='Test')),
                ('attempt', models.OneToOneField(blank=True, help_text="TestAttempt yaratilganda bog'lanadi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='admin_panel.testattempt', verbose_name='Test topshirish')),
            ],
            options={
                'verbose_name': 'Test yuborish',
                'verbose_name_plural': 'Test yuborishlar',
                'db_table': 'test_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choice', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='Tanlangan javob')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri")),
                ('points_earned', models.FloatField(default=0.0, verbose_name='Olingan ball')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Javob berilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='admin_panel.testquestion', verbose_name='Savol')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='admin_panel.testattempt', verbose_name='Test topshirish')),
            ],
            options={
                'verbose_name': 'Test javobi',
                'verbose_name_plural': 'Test javoblari',
                'db_table': 'test_answers',
            },
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['student', 'status'], name='test_attemp_student_357571_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'status'], name='test_attemp_test_id_3e23fc_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['status'], name='test_attemp_status_cd99a7_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['expires_at'], name='test_attemp_expires_b74408_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['test', 'student'], name='test_assign_test_id_e0e963_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['status'], name='test_assign_status_0ecfcb_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['test', 'status'], name='test_assign_test_id_5521a1_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['last_activity_at'], name='test_assign_last_ac_b73437_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testassignment',
            unique_together={('test', 'student')},
        ),
        migrations.AddIndex(
            model_name='testanswer',
            index=models.Index(fields=['attempt', 'question'], name='test_answer_attempt_b89a3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
