# Generated by Django 5.0.6 on 2026-01-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_testattempt_testassignment_testanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz')], help_text='Test tili (ixtiyoriy)', max_length=50, null=True, verbose_name='Til'),
        ),
        migrations.DeleteModel(
            name='TestAssignment',
        ),
    ]
