# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_testquestion_image_remove_image_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='type',
        ),
    ]
