# Generated by Django 5.0.6 on 2026-02-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_referral_fields_and_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kanal nomi')),
                ('channel_id', models.CharField(max_length=255, unique=True, verbose_name='Kanal ID/Username')),
                ('channel_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kanal havolasi (username)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Majburiy kanal',
                'verbose_name_plural': 'Majburiy kanallar',
                'db_table': 'mandatory_channels',
            },
        ),
        migrations.CreateModel(
            name='StudentRating',
            fields=[
            ],
            options={
                'verbose_name': 'Reyting',
                'verbose_name_plural': 'Reyting',
                'ordering': ['-referral_points', '-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin_panel.student',),
        ),
        migrations.RenameIndex(
            model_name='referral',
            new_name='referrals_referre_f47e8e_idx',
            old_name='referrals_referre_idx',
        ),
        migrations.RenameIndex(
            model_name='referral',
            new_name='referrals_created_995256_idx',
            old_name='referrals_created_idx',
        ),
    ]
