# Generated by Django 5.0.6 on 2026-02-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_mandatorychannel_studentrating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.TextField(default='', verbose_name='Matn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('suggestion', 'Taklif'), ('complaint', 'Shikoyat')], default='suggestion', max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Metrika raqami'),
        ),
    ]
