# Generated by Django 5.0.6 on 2026-02-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_remove_feedback_message_remove_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='achievements_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='students/achievements/', verbose_name='Avvalgi yutuqlar fayli/rasmi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='students/', verbose_name='Rasm'),
        ),
    ]
