# Generated by Django 5.0.6 on 2026-02-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_alter_student_achievements_file_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='initial_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism-familiya (Registratsiya)'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_owner',
            field=models.CharField(blank=True, choices=[('ozimniki', "O'zimniki"), ('turmush_ortogim', "Turmush o'rtog'im"), ('boshqa', 'Boshqa')], max_length=50, null=True, verbose_name='Telefon egasi'),
        ),
    ]
