# Generated by Django 5.0.6 on 2026-02-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_student_initial_full_name_student_phone_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_grade_5', models.BooleanField(default=False, verbose_name='5-sinf')),
                ('target_grade_6', models.BooleanField(default=False, verbose_name='6-sinf')),
                ('target_grade_7', models.BooleanField(default=False, verbose_name='7-sinf')),
                ('target_grade_8', models.BooleanField(default=False, verbose_name='8-sinf')),
                ('message', models.TextField(help_text="Markdown formatini qo'llab quvvatlaydi. {student_name} - o'quvchi ismi o'rniga tushadi.", verbose_name='Xabar matni')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('sending', 'Yuborilmoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xatolik')], default='draft', max_length=20, verbose_name='Holat')),
                ('recipient_count', models.IntegerField(default=0, verbose_name='Qabul qiluvchilar')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Yuborildi')),
                ('blocked_count', models.IntegerField(default=0, verbose_name='Bloklaganlar')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Xatoliklar')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Xabarnoma',
                'verbose_name_plural': 'Xabarnomalar',
                'db_table': 'broadcast_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
