# Generated by Django 5.0.6 on 2026-02-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_test_optional_grade_and_target_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsource',
            name='source_type',
            field=models.CharField(choices=[('by_rahimov_school', 'Rahimov School sahifalaridan'), ('instagram', 'Instagram'), ('telegram_ads', 'Telegram Ads'), ('telegram_channel', 'Telegram kanal'), ('by_friend', 'Tanish orqali'), ('boshqa', 'Boshqa')], max_length=100, verbose_name='Manba turi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, choices=[('Andijon', 'Andijon viloyati'), ('Buxoro', 'Buxoro viloyati'), ("Farg'ona", "Farg'ona viloyati"), ('Jizzax', 'Jizzax viloyati'), ('Namangan', 'Namangan viloyati'), ('Navoiy', 'Navoiy viloyati'), ('Qashqadaryo', 'Qashqadaryo viloyati'), ('Samarqand', 'Samarqand viloyati'), ('Sirdaryo', 'Sirdaryo viloyati'), ('Surxondaryo', 'Surxondaryo viloyati'), ('Toshkent', 'Toshkent viloyati'), ('Toshkent shahar', 'Toshkent shahar'), ('Xorazm', 'Xorazm viloyati'), ("Qoraqalpog'iston", "Qoraqalpog'iston")], max_length=255, null=True, verbose_name='Viloyat'),
        ),
    ]
