# Generated by Django 5.0.6 on 2026-02-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_add_student_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered_from_web',
            field=models.BooleanField(default=False, verbose_name="Web App orqali ro'yxatdan o'tgan"),
        ),
    ]
