# Generated by Django 5.0.6 on 2026-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_add_registered_from_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf'), (0, 'Boshqa')], null=True, verbose_name='Sinf'),
        ),
    ]
