# Generated by Django 5.0.6 on 2026-02-18 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_update_grade_add_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Rasm'), ('video', 'Video')], max_length=10, verbose_name='Media turi')),
                ('file', models.FileField(upload_to='broadcasts/', verbose_name='Fayl')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='admin_panel.broadcastmessage', verbose_name='Xabarnoma')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media fayllar',
                'db_table': 'broadcast_media',
                'ordering': ['order'],
            },
        ),
    ]
