# Generated by Django 5.0.6 on 2026-02-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_add_broadcast_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmedia',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Davomiylik (sek)'),
        ),
        migrations.AddField(
            model_name='broadcastmedia',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Balandlik (px)'),
        ),
        migrations.AddField(
            model_name='broadcastmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='broadcasts/thumbs/', verbose_name='Eskiz'),
        ),
        migrations.AddField(
            model_name='broadcastmedia',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kenglik (px)'),
        ),
    ]
