# Generated by Django 5.0.6 on 2026-02-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_add_broadcast_media_video_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='message',
            field=models.TextField(help_text="HTML formatini qo'llab quvvatlaydi (<b>qalin</b>, <i>kursiv</i>, <a href='...'>havola</a>). {student_name} - o'quvchi ismi o'rniga tushadi.", verbose_name='Xabar matni'),
        ),
    ]
