# Generated by Django 5.0.6 on 2026-02-18 12:47

import admin_panel.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_update_broadcast_message_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hamkor nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('referral_code', models.CharField(db_index=True, default=admin_panel.models._generate_partner_code, help_text='Avtomatik yaratiladi. t.me/BOT?start=ptr_XXXXXXXXXX', max_length=20, unique=True, verbose_name='Referal kodi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'db_table': 'partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Foydalanuvchi qaysi hamkor havolasi orqali kelgan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_students', to='admin_panel.partner', verbose_name='Hamkor'),
        ),
    ]
