# Generated by Django 5.0.6 on 2026-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_broadcastmessage_target_all_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Variant A'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Variant B'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Variant C'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Variant D'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Savol matni'),
        ),
    ]
