# Generated by Django 5.0.6 on 2026-02-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_alter_testquestion_option_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='finish_at',
            field=models.DateTimeField(blank=True, help_text='Agar belgilansa, test faqat shu vaqtdan oldin boshlanishi mumkin.', null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AddField(
            model_name='test',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Agar belgilansa, test faqat shu vaqtdan keyin boshlanishi mumkin.', null=True, verbose_name='Boshlanish vaqti'),
        ),
    ]
