# Generated by Django 5.0.6 on 2026-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_test_finish_at_test_starts_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.IntegerField(choices=[(1, 'Gooo'), (5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf')], verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 'Gooo'), (5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf')], null=True, verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='test',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 'Gooo'), (5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf')], help_text="Ixtiyoriy. Bo'sh qoldirsangiz, testni faqat tanlangan o'quvchilarga yuborishingiz mumkin.", null=True, verbose_name='Sinf'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active', 'created_at'], name='students_is_acti_a0d5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade', 'is_active'], name='students_grade_7b1b93_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['referrer'], name='students_referre_f02538_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['partner'], name='students_partner_eaf386_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['registered_from_web'], name='students_registe_ed05d8_idx'),
        ),
    ]
