# Generated by Django 5.0.6 on 2026-02-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_alter_exam_grade_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='error_log',
            field=models.TextField(blank=True, null=True, verbose_name='Xatoliklar tarixi'),
        ),
    ]
