# Generated by Django 5.0.6 on 2026-02-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_broadcastmessage_error_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', "O'zbek"), ('ru', 'Rus')], max_length=50, null=True, verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='test',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', "O'zbek"), ('ru', 'Rus')], help_text='Test tili (ixtiyoriy)', max_length=50, null=True, verbose_name='Til'),
        ),
    ]
