# Generated by Django 5.0.6 on 2026-02-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_alter_student_language_alter_test_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='blocked_count',
            field=models.IntegerField(default=0, help_text='Test yuborishda botni bloklagan foydalanuvchilar soni.', verbose_name='Bot bloklagan foydalanuvchilar soni'),
        ),
        migrations.AddField(
            model_name='test',
            name='blocked_users',
            field=models.JSONField(blank=True, default=list, help_text="Bot bloklagan foydalanuvchilar ro'yxati (telegram_id, ism). Avtomatik to'ldiriladi.", verbose_name="Bloklagan foydalanuvchilar ro'yxati"),
        ),
        migrations.AddField(
            model_name='test',
            name='sent_count',
            field=models.IntegerField(default=0, help_text="Test o'quvchilarga yuborilganda avtomatik yangilanadi.", verbose_name='Yuborilganlar soni'),
        ),
    ]
