# Generated by Django 5.0.6 on 2026-03-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_add_test_send_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='include_register_button',
            field=models.BooleanField(default=False, help_text="Xabar ostida maxsus Ro'yxatdan o'tish Web App tugmasi qo'shiladi.", verbose_name="Ro'yxatdan o'tish tugmasini qo'shish"),
        ),
    ]
